FROM node:22-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /usr/src/app/dist ./dist

# Copy local .env if available, otherwise it should be provided at runtime
# COPY .env .env

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
