export enum BillingStatusEnum {
  PENDING_OWNER_REVIEW = 'PENDING_OWNER_REVIEW',
  PENDING_TENANT_PAYMENT = 'PENDING_TENANT_PAYMENT',
  PAID = 'PAID',
}

export enum BillingTypeEnum {
  RECURRING = 'RECURRING',
  USAGE_BASED = 'USAGE_BASED',
}
